/* solhint-disable const-name-snakecase*/
/* solhint-disable state-visibility*/
pragma solidity 0.4.23;


contract Countries {
    bytes32 constant AF = 'AF'; // Afghanistan
    bytes32 constant AX = 'AX'; // Aland Islands
    bytes32 constant AL = 'AL'; // Albania
    bytes32 constant DZ = 'DZ'; // Algeria
    bytes32 constant AS = 'AS'; // American Samoa
    bytes32 constant AD = 'AD'; // Andorra
    bytes32 constant AO = 'AO'; // Angola
    bytes32 constant AI = 'AI'; // Anguilla
    bytes32 constant AQ = 'AQ'; // Antarctica
    bytes32 constant AG = 'AG'; // Antigua and Barbuda
    bytes32 constant AR = 'AR'; // Argentina
    bytes32 constant AM = 'AM'; // Armenia
    bytes32 constant AW = 'AW'; // Aruba
    bytes32 constant AU = 'AU'; // Australia
    bytes32 constant AT = 'AT'; // Austria
    bytes32 constant AZ = 'AZ'; // Azerbaijan
    bytes32 constant BS = 'BS'; // Bahamas
    bytes32 constant BH = 'BH'; // Bahrain
    bytes32 constant BD = 'BD'; // Bangladesh
    bytes32 constant BB = 'BB'; // Barbados
    bytes32 constant BY = 'BY'; // Belarus
    bytes32 constant BE = 'BE'; // Belgium
    bytes32 constant BZ = 'BZ'; // Belize
    bytes32 constant BJ = 'BJ'; // Benin
    bytes32 constant BM = 'BM'; // Bermuda
    bytes32 constant BT = 'BT'; // Bhutan
    bytes32 constant BO = 'BO'; // Bolivia
    bytes32 constant BA = 'BA'; // Bosnia and Herzegovina
    bytes32 constant BW = 'BW'; // Botswana
    bytes32 constant BV = 'BV'; // Bouvet Island
    bytes32 constant BR = 'BR'; // Brazil
    bytes32 constant VG = 'VG'; // British Virgin Islands
    bytes32 constant IO = 'IO'; // British Indian Ocean Territory
    bytes32 constant BN = 'BN'; // Brunei Darussalam
    bytes32 constant BG = 'BG'; // Bulgaria
    bytes32 constant BF = 'BF'; // Burkina Faso
    bytes32 constant BI = 'BI'; // Burundi
    bytes32 constant KH = 'KH'; // Cambodia
    bytes32 constant CM = 'CM'; // Cameroon
    bytes32 constant CA = 'CA'; // Canada
    bytes32 constant CV = 'CV'; // Cape Verde
    bytes32 constant KY = 'KY'; // Cayman Islands
    bytes32 constant CF = 'CF'; // Central African Republic
    bytes32 constant TD = 'TD'; // Chad
    bytes32 constant CL = 'CL'; // Chile
    bytes32 constant CN = 'CN'; // China
    bytes32 constant HK = 'HK'; // Hong Kong, SAR China
    bytes32 constant MO = 'MO'; // Macao, SAR China
    bytes32 constant CX = 'CX'; // Christmas Island
    bytes32 constant CC = 'CC'; // Cocos (Keeling) Islands
    bytes32 constant CO = 'CO'; // Colombia
    bytes32 constant KM = 'KM'; // Comoros
    bytes32 constant CG = 'CG'; // Congo (Brazzaville
    bytes32 constant CD = 'CD'; // Congo, (Kinshasa
    bytes32 constant CK = 'CK'; // Cook Islands
    bytes32 constant CR = 'CR'; // Costa Rica
    bytes32 constant CI = 'CI'; // Côte d'Ivoire, Ivory Coast
    bytes32 constant HR = 'HR'; // Croatia
    bytes32 constant CU = 'CU'; // Cuba
    bytes32 constant CY = 'CY'; // Cyprus
    bytes32 constant CZ = 'CZ'; // Czech Republic
    bytes32 constant DK = 'DK'; // Denmark
    bytes32 constant DJ = 'DJ'; // Djibouti
    bytes32 constant DM = 'DM'; // Dominica
    bytes32 constant DO = 'DO'; // Dominican Republic
    bytes32 constant EC = 'EC'; // Ecuador
    bytes32 constant EG = 'EG'; // Egypt
    bytes32 constant SV = 'SV'; // El Salvador
    bytes32 constant GQ = 'GQ'; // Equatorial Guinea
    bytes32 constant ER = 'ER'; // Eritrea
    bytes32 constant EE = 'EE'; // Estonia
    bytes32 constant ET = 'ET'; // Ethiopia
    bytes32 constant FK = 'FK'; // Falkland Islands (Malvinas)
    bytes32 constant FO = 'FO'; // Faroe Islands
    bytes32 constant FJ = 'FJ'; // Fiji
    bytes32 constant FI = 'FI'; // Finland
    bytes32 constant FR = 'FR'; // France
    bytes32 constant GF = 'GF'; // French Guiana
    bytes32 constant PF = 'PF'; // French Polynesia
    bytes32 constant TF = 'TF'; // French Southern Territories
    bytes32 constant GA = 'GA'; // Gabon
    bytes32 constant GM = 'GM'; // Gambia
    bytes32 constant GE = 'GE'; // Georgia
    bytes32 constant DE = 'DE'; // Germany
    bytes32 constant GH = 'GH'; // Ghana
    bytes32 constant GI = 'GI'; // Gibraltar
    bytes32 constant GR = 'GR'; // Greece
    bytes32 constant GL = 'GL'; // Greenland
    bytes32 constant GD = 'GD'; // Grenada
    bytes32 constant GP = 'GP'; // Guadeloupe
    bytes32 constant GU = 'GU'; // Guam
    bytes32 constant GT = 'GT'; // Guatemala
    bytes32 constant GG = 'GG'; // Guernsey
    bytes32 constant GN = 'GN'; // Guinea
    bytes32 constant GW = 'GW'; // Guinea-Bissau
    bytes32 constant GY = 'GY'; // Guyana
    bytes32 constant HT = 'HT'; // Haiti
    bytes32 constant HM = 'HM'; // Heard and Mcdonald Islands
    bytes32 constant VA = 'VA'; // Holy See (Vatican City State)
    bytes32 constant HN = 'HN'; // Honduras
    bytes32 constant HU = 'HU'; // Hungary
    bytes32 constant IS = 'IS'; // Iceland
    bytes32 constant IN = 'IN'; // India
    bytes32 constant ID = 'ID'; // Indonesia
    bytes32 constant IR = 'IR'; // Iran, Islamic Republic of
    bytes32 constant IQ = 'IQ'; // Iraq
    bytes32 constant IE = 'IE'; // Ireland
    bytes32 constant IM = 'IM'; // Isle of Man
    bytes32 constant IL = 'IL'; // Israel
    bytes32 constant IT = 'IT'; // Italy
    bytes32 constant JM = 'JM'; // Jamaica
    bytes32 constant JP = 'JP'; // Japan
    bytes32 constant JE = 'JE'; // Jersey
    bytes32 constant JO = 'JO'; // Jordan
    bytes32 constant KZ = 'KZ'; // Kazakhstan
    bytes32 constant KE = 'KE'; // Kenya
    bytes32 constant KI = 'KI'; // Kiribati
    bytes32 constant KP = 'KP'; // Korea (North)
    bytes32 constant KR = 'KR'; // Korea (South)
    bytes32 constant XK = 'XK'; // Kosovo
    bytes32 constant KW = 'KW'; // Kuwait
    bytes32 constant KG = 'KG'; // Kyrgyzstan
    bytes32 constant LA = 'LA'; // Lao PDR
    bytes32 constant LV = 'LV'; // Latvia
    bytes32 constant LB = 'LB'; // Lebanon
    bytes32 constant LS = 'LS'; // Lesotho
    bytes32 constant LR = 'LR'; // Liberia
    bytes32 constant LY = 'LY'; // Libya
    bytes32 constant LI = 'LI'; // Liechtenstein
    bytes32 constant LT = 'LT'; // Lithuania
    bytes32 constant LU = 'LU'; // Luxembourg
    bytes32 constant MK = 'MK'; // Macedonia, Republic of
    bytes32 constant MG = 'MG'; // Madagascar
    bytes32 constant MW = 'MW'; // Malawi
    bytes32 constant MY = 'MY'; // Malaysia
    bytes32 constant MV = 'MV'; // Maldives
    bytes32 constant ML = 'ML'; // Mali
    bytes32 constant MT = 'MT'; // Malta
    bytes32 constant MH = 'MH'; // Marshall Islands
    bytes32 constant MQ = 'MQ'; // Martinique
    bytes32 constant MR = 'MR'; // Mauritania
    bytes32 constant MU = 'MU'; // Mauritius
    bytes32 constant YT = 'YT'; // Mayotte
    bytes32 constant MX = 'MX'; // Mexico
    bytes32 constant FM = 'FM'; // Micronesia, Federated States of
    bytes32 constant MD = 'MD'; // Moldova
    bytes32 constant MC = 'MC'; // Monaco
    bytes32 constant MN = 'MN'; // Mongolia
    bytes32 constant ME = 'ME'; // Montenegro
    bytes32 constant MS = 'MS'; // Montserrat
    bytes32 constant MA = 'MA'; // Morocco
    bytes32 constant MZ = 'MZ'; // Mozambique
    bytes32 constant MM = 'MM'; // Myanmar
    bytes32 constant NA = 'NA'; // Namibia
    bytes32 constant NR = 'NR'; // Nauru
    bytes32 constant NP = 'NP'; // Nepal
    bytes32 constant NL = 'NL'; // Netherlands
    bytes32 constant AN = 'AN'; // Netherlands Antilles
    bytes32 constant NC = 'NC'; // New Caledonia
    bytes32 constant NZ = 'NZ'; // New Zealand
    bytes32 constant NI = 'NI'; // Nicaragua
    bytes32 constant NE = 'NE'; // Niger
    bytes32 constant NG = 'NG'; // Nigeria
    bytes32 constant NU = 'NU'; // Niue
    bytes32 constant NF = 'NF'; // Norfolk Island
    bytes32 constant MP = 'MP'; // Northern Mariana Islands
    bytes32 constant NO = 'NO'; // Norway
    bytes32 constant OM = 'OM'; // Oman
    bytes32 constant PK = 'PK'; // Pakistan
    bytes32 constant PW = 'PW'; // Palau
    bytes32 constant PS = 'PS'; // Palestinian Territory
    bytes32 constant PA = 'PA'; // Panama
    bytes32 constant PG = 'PG'; // Papua New Guinea
    bytes32 constant PY = 'PY'; // Paraguay
    bytes32 constant PE = 'PE'; // Peru
    bytes32 constant PH = 'PH'; // Philippines
    bytes32 constant PN = 'PN'; // Pitcairn
    bytes32 constant PL = 'PL'; // Poland
    bytes32 constant PT = 'PT'; // Portugal
    bytes32 constant PR = 'PR'; // Puerto Rico
    bytes32 constant QA = 'QA'; // Qatar
    bytes32 constant RE = 'RE'; // Réunion
    bytes32 constant RO = 'RO'; // Romania
    bytes32 constant RU = 'RU'; // Russian Federation
    bytes32 constant RW = 'RW'; // Rwanda
    bytes32 constant BL = 'BL'; // Saint-Barthélemy
    bytes32 constant SH = 'SH'; // Saint Helena
    bytes32 constant KN = 'KN'; // Saint Kitts and Nevis
    bytes32 constant LC = 'LC'; // Saint Lucia
    bytes32 constant MF = 'MF'; // Saint-Martin (French part
    bytes32 constant PM = 'PM'; // Saint Pierre and Miquelon
    bytes32 constant VC = 'VC'; // Saint Vincent and Grenadines
    bytes32 constant WS = 'WS'; // Samoa
    bytes32 constant SM = 'SM'; // San Marino
    bytes32 constant ST = 'ST'; // Sao Tome and Principe
    bytes32 constant SA = 'SA'; // Saudi Arabia
    bytes32 constant SN = 'SN'; // Senegal
    bytes32 constant RS = 'RS'; // Serbia
    bytes32 constant SC = 'SC'; // Seychelles
    bytes32 constant SL = 'SL'; // Sierra Leone
    bytes32 constant SG = 'SG'; // Singapore
    bytes32 constant SK = 'SK'; // Slovakia
    bytes32 constant SI = 'SI'; // Slovenia
    bytes32 constant SB = 'SB'; // Solomon Islands
    bytes32 constant SO = 'SO'; // Somalia
    bytes32 constant ZA = 'ZA'; // South Africa
    bytes32 constant GS = 'GS'; // South Georgia and the South Sandwich Islands
    bytes32 constant SS = 'SS'; // South Sudan
    bytes32 constant ES = 'ES'; // Spain
    bytes32 constant LK = 'LK'; // Sri Lanka
    bytes32 constant SD = 'SD'; // Sudan
    bytes32 constant SR = 'SR'; // Suriname
    bytes32 constant SJ = 'SJ'; // Svalbard and Jan Mayen Islands
    bytes32 constant SZ = 'SZ'; // Swaziland
    bytes32 constant SE = 'SE'; // Sweden
    bytes32 constant CH = 'CH'; // Switzerland
    bytes32 constant SY = 'SY'; // Syrian Arab Republic (Syria
    bytes32 constant TW = 'TW'; // Taiwan, Republic of China
    bytes32 constant TJ = 'TJ'; // Tajikistan
    bytes32 constant TZ = 'TZ'; // Tanzania, United Republic of
    bytes32 constant TH = 'TH'; // Thailand
    bytes32 constant TL = 'TL'; // Timor-Leste
    bytes32 constant TG = 'TG'; // Togo
    bytes32 constant TK = 'TK'; // Tokelau
    bytes32 constant TO = 'TO'; // Tonga
    bytes32 constant TT = 'TT'; // Trinidad and Tobago
    bytes32 constant TN = 'TN'; // Tunisia
    bytes32 constant TR = 'TR'; // Turkey
    bytes32 constant TM = 'TM'; // Turkmenistan
    bytes32 constant TC = 'TC'; // Turks and Caicos Islands
    bytes32 constant TV = 'TV'; // Tuvalu
    bytes32 constant UG = 'UG'; // Uganda
    bytes32 constant UA = 'UA'; // Ukraine
    bytes32 constant AE = 'AE'; // United Arab Emirates
    bytes32 constant GB = 'GB'; // United Kingdom
    bytes32 constant US = 'US'; // United States of America
    bytes32 constant UM = 'UM'; // US Minor Outlying Islands
    bytes32 constant UY = 'UY'; // Uruguay
    bytes32 constant UZ = 'UZ'; // Uzbekistan
    bytes32 constant VU = 'VU'; // Vanuatu
    bytes32 constant VE = 'VE'; // Venezuela (Bolivarian Republic)
    bytes32 constant VN = 'VN'; // Viet Nam
    bytes32 constant VI = 'VI'; // Virgin Islands, US
    bytes32 constant WF = 'WF'; // Wallis and Futuna Islands
    bytes32 constant EH = 'EH'; // Western Sahara
    bytes32 constant YE = 'YE'; // Yemen
    bytes32 constant ZM = 'ZM'; // Zambia
    bytes32 constant ZW = 'ZW'; // Zimbabwe

    bytes32 constant Afghanistan = AF;
    bytes32 constant AlandIslands = AX;
    bytes32 constant Albania = AL;
    bytes32 constant Algeria = DZ;
    bytes32 constant AmericanSamoa = AS;
    bytes32 constant Andorra = AD;
    bytes32 constant Angola = AO;
    bytes32 constant Anguilla = AI;
    bytes32 constant Antarctica = AQ;
    bytes32 constant AntiguaAndBarbuda = AG;
    bytes32 constant Argentina = AR;
    bytes32 constant Armenia = AM;
    bytes32 constant Aruba = AW;
    bytes32 constant Australia = AU;
    bytes32 constant Austria = AT;
    bytes32 constant Azerbaijan = AZ;
    bytes32 constant Bahamas = BS;
    bytes32 constant Bahrain = BH;
    bytes32 constant Bangladesh = BD;
    bytes32 constant Barbados = BB;
    bytes32 constant Belarus = BY;
    bytes32 constant Belgium = BE;
    bytes32 constant Belize = BZ;
    bytes32 constant Benin = BJ;
    bytes32 constant Bermuda = BM;
    bytes32 constant Bhutan = BT;
    bytes32 constant Bolivia = BO;
    bytes32 constant BosniaAndHerzegovina = BA;
    bytes32 constant Botswana = BW;
    bytes32 constant BouvetIsland = BV;
    bytes32 constant Brazil = BR;
    bytes32 constant BritishVirginIslands = VG;
    bytes32 constant BritishIndianOceanTerritory = IO;
    bytes32 constant BruneiDarussalam = BN;
    bytes32 constant Bulgaria = BG;
    bytes32 constant BurkinaFaso = BF;
    bytes32 constant Burundi = BI;
    bytes32 constant Cambodia = KH;
    bytes32 constant Cameroon = CM;
    bytes32 constant Canada = CA;
    bytes32 constant CapeVerde = CV;
    bytes32 constant CaymanIslands = KY;
    bytes32 constant CentralAfricanRepublic = CF;
    bytes32 constant Chad = TD;
    bytes32 constant Chile = CL;
    bytes32 constant China = CN;
    bytes32 constant HongKongSARChina = HK;
    bytes32 constant MacaoSARChina = MO;
    bytes32 constant ChristmasIsland = CX;
    bytes32 constant CocosKeelingIslands = CC;
    bytes32 constant Colombia = CO;
    bytes32 constant Comoros = KM;
    bytes32 constant CongoBrazzaville = CG;
    bytes32 constant CongoKinshasa = CD;
    bytes32 constant CookIslands = CK;
    bytes32 constant CostaRica = CR;
    bytes32 constant CotedIvoire = CI; // Ivory Coast
    bytes32 constant Croatia = HR;
    bytes32 constant Cuba = CU;
    bytes32 constant Cyprus = CY;
    bytes32 constant CzechRepublic = CZ;
    bytes32 constant Denmark = DK;
    bytes32 constant Djibouti = DJ;
    bytes32 constant Dominica = DM;
    bytes32 constant DominicanRepublic = DO;
    bytes32 constant Ecuador = EC;
    bytes32 constant Egypt = EG;
    bytes32 constant ElSalvador = SV;
    bytes32 constant EquatorialGuinea = GQ;
    bytes32 constant Eritrea = ER;
    bytes32 constant Estonia = EE;
    bytes32 constant Ethiopia = ET;
    bytes32 constant FalklandIslandsMalvinas = FK;
    bytes32 constant FaroeIslands = FO;
    bytes32 constant Fiji = FJ;
    bytes32 constant Finland = FI;
    bytes32 constant France = FR;
    bytes32 constant FrenchGuiana = GF;
    bytes32 constant FrenchPolynesia = PF;
    bytes32 constant FrenchSouthernTerritories = TF;
    bytes32 constant Gabon = GA;
    bytes32 constant Gambia = GM;
    bytes32 constant Georgia = GE;
    bytes32 constant Germany = DE;
    bytes32 constant Ghana = GH;
    bytes32 constant Gibraltar = GI;
    bytes32 constant Greece = GR;
    bytes32 constant Greenland = GL;
    bytes32 constant Grenada = GD;
    bytes32 constant Guadeloupe = GP;
    bytes32 constant Guam = GU;
    bytes32 constant Guatemala = GT;
    bytes32 constant Guernsey = GG;
    bytes32 constant Guinea = GN;
    bytes32 constant GuineaBissau = GW;
    bytes32 constant Guyana = GY;
    bytes32 constant Haiti = HT;
    bytes32 constant HeardAndMcdonaldIslands = HM;
    bytes32 constant HolySeeVaticanCityState = VA;
    bytes32 constant Honduras = HN;
    bytes32 constant Hungary = HU;
    bytes32 constant Iceland = IS;
    bytes32 constant India = IN;
    bytes32 constant Indonesia = ID;
    bytes32 constant IranIslamicRepublicOf = IR;
    bytes32 constant Iraq = IQ;
    bytes32 constant Ireland = IE;
    bytes32 constant IsleOfMan = IM;
    bytes32 constant Israel = IL;
    bytes32 constant Italy = IT;
    bytes32 constant Jamaica = JM;
    bytes32 constant Japan = JP;
    bytes32 constant Jersey = JE;
    bytes32 constant Jordan = JO;
    bytes32 constant Kazakhstan = KZ;
    bytes32 constant Kenya = KE;
    bytes32 constant Kiribati = KI;
    bytes32 constant KoreaNorth = KP;
    bytes32 constant KoreaSouth = KR;
    bytes32 constant Kosovo = XK;
    bytes32 constant Kuwait = KW;
    bytes32 constant Kyrgyzstan = KG;
    bytes32 constant LaoPDR = LA;
    bytes32 constant Latvia = LV;
    bytes32 constant Lebanon = LB;
    bytes32 constant Lesotho = LS;
    bytes32 constant Liberia = LR;
    bytes32 constant Libya = LY;
    bytes32 constant Liechtenstein = LI;
    bytes32 constant Lithuania = LT;
    bytes32 constant Luxembourg = LU;
    bytes32 constant MacedoniaRepublicOf = MK;
    bytes32 constant Madagascar = MG;
    bytes32 constant Malawi = MW;
    bytes32 constant Malaysia = MY;
    bytes32 constant Maldives = MV;
    bytes32 constant Mali = ML;
    bytes32 constant Malta = MT;
    bytes32 constant MarshallIslands = MH;
    bytes32 constant Martinique = MQ;
    bytes32 constant Mauritania = MR;
    bytes32 constant Mauritius = MU;
    bytes32 constant Mayotte = YT;
    bytes32 constant Mexico = MX;
    bytes32 constant MicronesiaFederatedStatesOf = FM;
    bytes32 constant Moldova = MD;
    bytes32 constant Monaco = MC;
    bytes32 constant Mongolia = MN;
    bytes32 constant Montenegro = ME;
    bytes32 constant Montserrat = MS;
    bytes32 constant Morocco = MA;
    bytes32 constant Mozambique = MZ;
    bytes32 constant Myanmar = MM;
    bytes32 constant Namibia = NA;
    bytes32 constant Nauru = NR;
    bytes32 constant Nepal = NP;
    bytes32 constant Netherlands = NL;
    bytes32 constant NetherlandsAntilles = AN;
    bytes32 constant NewCaledonia = NC;
    bytes32 constant NewZealand = NZ;
    bytes32 constant Nicaragua = NI;
    bytes32 constant Niger = NE;
    bytes32 constant Nigeria = NG;
    bytes32 constant Niue = NU;
    bytes32 constant NorfolkIsland = NF;
    bytes32 constant NorthernMarianaIslands = MP;
    bytes32 constant Norway = NO;
    bytes32 constant Oman = OM;
    bytes32 constant Pakistan = PK;
    bytes32 constant Palau = PW;
    bytes32 constant PalestinianTerritory = PS;
    bytes32 constant Panama = PA;
    bytes32 constant PapuaNewGuinea = PG;
    bytes32 constant Paraguay = PY;
    bytes32 constant Peru = PE;
    bytes32 constant Philippines = PH;
    bytes32 constant Pitcairn = PN;
    bytes32 constant Poland = PL;
    bytes32 constant Portugal = PT;
    bytes32 constant PuertoRico = PR;
    bytes32 constant Qatar = QA;
    bytes32 constant Reunion = RE;
    bytes32 constant Romania = RO;
    bytes32 constant RussianFederation = RU;
    bytes32 constant Rwanda = RW;
    bytes32 constant SaintBarthelemy = BL;
    bytes32 constant SaintHelena = SH;
    bytes32 constant SaintKittsAndNevis = KN;
    bytes32 constant SaintLucia = LC;
    bytes32 constant SaintMartinFrenchPart = MF;
    bytes32 constant SaintPierreAndMiquelon = PM;
    bytes32 constant SaintVincentAndGrenadines = VC;
    bytes32 constant Samoa = WS;
    bytes32 constant SanMarino = SM;
    bytes32 constant SaoTomeAndPrincipe = ST;
    bytes32 constant SaudiArabia = SA;
    bytes32 constant Senegal = SN;
    bytes32 constant Serbia = RS;
    bytes32 constant Seychelles = SC;
    bytes32 constant SierraLeone = SL;
    bytes32 constant Singapore = SG;
    bytes32 constant Slovakia = SK;
    bytes32 constant Slovenia = SI;
    bytes32 constant SolomonIslands = SB;
    bytes32 constant Somalia = SO;
    bytes32 constant SouthAfrica = ZA;
    bytes32 constant SouthGeorgiaAndTheSouthSandwichIslands = GS;
    bytes32 constant SouthSudan = SS;
    bytes32 constant Spain = ES;
    bytes32 constant SriLanka = LK;
    bytes32 constant Sudan = SD;
    bytes32 constant Suriname = SR;
    bytes32 constant SvalbardAndJanMayenIslands = SJ;
    bytes32 constant Swaziland = SZ;
    bytes32 constant Sweden = SE;
    bytes32 constant Switzerland = CH;
    bytes32 constant SyrianArabRepublicSyria = SY;
    bytes32 constant TaiwanRepublicOfChina = TW;
    bytes32 constant Tajikistan = TJ;
    bytes32 constant TanzaniaUnitedRepublicOf = TZ;
    bytes32 constant Thailand = TH;
    bytes32 constant TimorLeste = TL;
    bytes32 constant Togo = TG;
    bytes32 constant Tokelau = TK;
    bytes32 constant Tonga = TO;
    bytes32 constant TrinidadAndTobago = TT;
    bytes32 constant Tunisia = TN;
    bytes32 constant Turkey = TR;
    bytes32 constant Turkmenistan = TM;
    bytes32 constant TurksAndCaicosIslands = TC;
    bytes32 constant Tuvalu = TV;
    bytes32 constant Uganda = UG;
    bytes32 constant Ukraine = UA;
    bytes32 constant UnitedArabEmirates = AE;
    bytes32 constant UnitedKingdom = GB;
    bytes32 constant UnitedStatesOfAmerica = US;
    bytes32 constant USMinorOutlyingIslands = UM;
    bytes32 constant Uruguay = UY;
    bytes32 constant Uzbekistan = UZ;
    bytes32 constant Vanuatu = VU;
    bytes32 constant VenezuelaBolivarianRepublic = VE;
    bytes32 constant VietNam = VN;
    bytes32 constant VirginIslandsUS = VI;
    bytes32 constant WallisAndFutunaIslands = WF;
    bytes32 constant WesternSahara = EH;
    bytes32 constant Yemen = YE;
    bytes32 constant Zambia = ZM;
    bytes32 constant Zimbabwe = ZW;

    bytes32 constant Unknown = '';

    function _isEU(bytes32 _country) internal pure returns(bool) {
        return _country == Austria
            || _country == Belgium
            || _country == Bulgaria
            || _country == Croatia
            || _country == Cyprus
            || _country == CzechRepublic
            || _country == Denmark
            || _country == Estonia
            || _country == Finland
            || _country == France
            || _country == Germany
            || _country == Greece
            || _country == Hungary
            || _country == Ireland
            || _country == Italy
            || _country == Latvia
            || _country == Lithuania
            || _country == Luxembourg
            || _country == Malta
            || _country == Netherlands
            || _country == Poland
            || _country == Portugal
            || _country == Romania
            || _country == Slovakia
            || _country == Slovenia
            || _country == Spain
            || _country == Sweden
            || _country == UnitedKingdom;
    }
}
